application:
  subdomain: wechat-article
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://wechat-article:3000/

services:
  wechat-article:
    # upstream: ghcr.io/wechat-article/wechat-article-exporter:v2.3.21
    image: ghcr.1ms.run/wechat-article/wechat-article-exporter:v2.3.21
    binds:
      - /lzcapp/var/data:/app/.data
