package: community.lazycat.app.wechat-article
version: 2.3.6
name: 公众号文章下载
description: "一款 开源 & 免费 的公众号文章下载神器"
min_os_version: "1.5.0"
homepage: https://github.com/wechat-article/wechat-article-exporter
author: wechat-article
unsupported_platforms:
  - ios
  - android
  - tvos
locales:
  zh:
    name: "公众号文章下载"
    description: "一款 开源 & 免费 的公众号文章下载神器"
  en:
    name: "WeChat Article Downloader"
    description: "An open-source and free tool for batch downloading WeChat official account articles"
